//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubDBApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddingToPubs
    {
        public string name { get; set; }
        public int building_no { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
    }
}
