//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubDBApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersView
    {
        public int id { get; set; }
        public string warehouse_name { get; set; }
        public string pub_name { get; set; }
        public string producer_name { get; set; }
        public string Incoming_Outcoming { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public decimal total { get; set; }
    }
}
