//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubDBApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsView
    {
        public int id { get; set; }
        public string name { get; set; }
        public string producer_name { get; set; }
        public decimal price { get; set; }
        public int alcohol_percentage { get; set; }
        public float volume { get; set; }
        public int RowVersion { get; set; }
    }
}
