//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubDBApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PubDBEntities : DbContext
    {
        public PubDBEntities()
            : base("name=PubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Magazines> Magazines { get; set; }
        public virtual DbSet<Magazines_Stock> Magazines_Stock { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Producents> Producents { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Pubs> Pubs { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
