//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubDBApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pubs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pubs()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Required")]
        public string name { get; set; }
        public int adress_id { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$",
        ErrorMessage = "Provide correct email address (e.g. jan.kowalski@wp.pl)")]
        public string e_mail { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^[0-9]{3}\-[0-9]{3}\-[0-9]{3}$",
        ErrorMessage = "Provide correct telephone number (e.g. 545-039-231)")]
        public string telephone_no { get; set; }
        public int RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Address Address { get; set; }
    }
}
